name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-17"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODAwOTJhMTMtOTA1ZC00NGIxLTkzYTktN2YwYjlmYjk1MzczIiwidGVuYW50X2lkIjoiYzI5ZDY5OWNhNmViNTk0M2JmZGI4ZmI2MjU2ODg0YzFjN2RjMTM2MmUyNWIxODYxNzMzZWQxYmI1OWY0ZWE5ZiIsImludGVybmFsX3NlY3JldCI6ImZmNGY1ZTIzLWE2Y2MtNDVkYi05MWQ2LWM3NjBjYjNjMzQxZCJ9.sJoJKpY9N_DdMzC6zUQxFLv5xtpAQtRCAfjBrjun5SY"

JWT_SECRET = "anubhavsingh"