name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-19"



# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjM0NjEwNjktYzUzOC00MDViLTkwYjgtM2RiZWM0YWVhMDQwIiwidGVuYW50X2lkIjoiZjc3OWFjODY1NmQ5MGM5YjYwYWI3Mzc1M2YwMWM2NjA0YjM0NGRhY2QxNGJkNmY5ZDg1OWIwNTRmMWI3ODIxMCIsImludGVybmFsX3NlY3JldCI6ImFhODkzMzhhLTRhMzItNGUxZS1hOTc3LTE0YTY4ZjJhMjJlNiJ9.JOXsOYrCYmJwNI__sne95jVJD_WnpHqpmhb1ptxZceE"

JWT_SECRET = "anubhavx"