name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-05"


# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOGY0YWNjMGMtMDU0NC00MDliLTg1NzEtZjc0MzQ2OWFkODI1IiwidGVuYW50X2lkIjoiMTIxYTQ5MDAyZGQwODliYjkzYWQyZjQxNDUxMDEwYzNmZjUwMmM5OGU2NzYxNmU5MTA0OTVmMGY3MGJjYThmYyIsImludGVybmFsX3NlY3JldCI6ImU5YjEyMmY1LWI3NmYtNDQwZC05NjE5LWE1MDUyODUzYjY2NiJ9.1gvdLL9_YILgqQwefKq2XqalQ6FBP_aBlK2Lf9AGjdc"

JWT_SECRET = "anubhavxsingh"


